# Selection

## DataFrames

In [29]:
import pandas as pd
from pandas import DataFrame, Series
import numpy as np

Create a DataFrame for the variable df, useing {'AAA': [4, 5, 6, 7], 'BBB': [10, 20, 30, 40], 'CCC': [100, 50, -30, -50]}

In [125]:
df = DataFrame({'AAA' :[4,5,6,7], 'BBB': [10, 20, 30, 40], 'CCC': [100, 50, -30, -5]}) ; df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40   -5

In [127]:
df2 = DataFrame({'Wangshi' :[4], 'ZeGuang': [10], 'Yanmei': [100]}) ; df2

Wangshi  Yanmei  ZeGuang
0        4     100       10

About df, if 1, 2 is in the index, return the Boolean value

In [39]:
df.index.isin([1,2])

array([False,  True,  True, False], dtype=bool)

About df, aggregation boolean sequence, use the previous boolean array and AAA columns is <= 6, return the boolean Series

In [40]:
(df.index.isin([1, 2])) & (df.AAA <= 6)

0    False
1     True
2     True
3    False
Name: AAA, dtype: bool

About df, selection rows with index 0,2,4 and columns AAA >= 6, return DataFrame

In [43]:
df.loc[(df.index.isin([0, 2, 4])) & (df.AAA >= 6)]

AAA  BBB  CCC
2    6   30  -30

---

Create a dict for the variable data, {'AAA': [4, 5, 6, 7], 'BBB': [10, 20, 30, 40], 'CCC': [100, 50, -30, -50]}

In [44]:
data = {'AAA': [4,5,6,7], 'BBB': [10,20,30,40], 'CCC': [100, 50, -30, -50]} ; data

{'AAA': [4, 5, 6, 7], 'BBB': [10, 20, 30, 40], 'CCC': [100, 50, -30, -50]}

Create a DataFrame for the variable df_d, the data is from data variable, the index is 'foo', 'bar', 'boo', 'kar'

In [45]:
df_d = DataFrame(data = data, index = ['foo', 'bar', 'boo', 'kar']) ; df_d

AAA  BBB  CCC
foo    4   10  100
bar    5   20   50
boo    6   30  -30
kar    7   40  -50

About df_d, Inverse the selection rows with index is 'foo', 'boo' and columns AAA <= 6

In [129]:
df_d.loc[~((df_d.AAA <= 6) & (df_d.index.isin(['foo', 'boo'])))]

AAA  BBB  CCC
bar    5   20   50
kar    7   40  -50

About df_d, selection rows with position 0~3

In [49]:
df_d.iloc[0:3]

AAA  BBB  CCC
foo    4   10  100
bar    5   20   50
boo    6   30  -30

About df_d, selection rows with index 'bar'~'kar'

In [50]:
df_d.loc['bar':'kar']

AAA  BBB  CCC
bar    5   20   50
boo    6   30  -30
kar    7   40  -50

About df, selection rows with position 1~3

In [51]:
df.iloc[1:3]

AAA  BBB  CCC
1    5   20   50
2    6   30  -30

About df, selection rows with index 1~3

In [52]:
df.loc[1:3]

AAA  BBB  CCC
1    5   20   50
2    6   30  -30
3    7   40  -50

## Panels

Creat a Series for the variable rng, the index is start at 1/1/2014, the periods is 100, the freq is 'D'

In [80]:
rng = pd.date_range(start='1/1/2013', periods=100, freq='D') ; rng[:3]

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03'], dtype='datetime64[ns]', freq='D')

Creat a random array for the variable data, looks like [100[4]]

In [81]:
data = np.random.randn(100, 4) ; data[1]

array([-1.69862817,  0.1403932 ,  1.44044611,  1.33804698])

Creat a list for the variable cols, 'A', 'B', 'C', 'D'

In [82]:
cols = ['A', 'B', 'C', 'D'] ; cols

['A', 'B', 'C', 'D']

Creat three DataFrame for the variables df1, df2, df3, data is from variable data, index is from variable rng, columns is from variable cols

In [83]:
df1 = DataFrame(data=data, index=rng, columns=cols)
df2 = df1.copy()
df3 = df1.copy()
df3.head(1)

A         B         C         D
2013-01-01  0.270417  0.834448  2.399968 -1.820099

Creat a Panel for variable pf, useing variable df1, df2, df3 as Panel Items and names is df1, df2, df3

In [86]:
pf = pd.Panel({'df1': df1, 'df2': df2, 'df3': df3}) ; pf

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 100 (major_axis) x 4 (minor_axis)
Items axis: df1 to df3
Major_axis axis: 2013-01-01 00:00:00 to 2013-04-10 00:00:00
Minor_axis axis: A to D

## New Columns

Creat a DataFrame for variable df_new_cols, use {'AAA': [1,2,1,3], 'BBB': [1,1,2,2], 'CCC': [2,1,3,1]}

In [87]:
df_new_cols = DataFrame({'AAA': [1,2,1,3], 'BBB': [1,1,2,2], 'CCC':[2,1,3,1]}) ; df_new_cols

AAA  BBB  CCC
0    1    1    2
1    2    1    1
2    1    2    3
3    3    2    1

About df_new_cols, Creat a Index for variable source_cols, use the columns

In [88]:
source_cols = df_new_cols.columns ; source_cols

Index(['AAA', 'BBB', 'CCC'], dtype='object')

About df_new_cols, Creat a list for variable new_cols, use the columns value + '_cat'

In [90]:
new_cols = [str(x) + '_cat' for x in source_cols] ; new_cols

['AAA_cat', 'BBB_cat', 'CCC_cat']

Creat a dict for variable categories, use {1: 'Alpha', 2: 'Beta', 3: 'Charlie'}

In [91]:
categories = {1: 'Alpha', 2: 'Beat', 3: 'Charlie'} ; categories

{1: 'Alpha', 2: 'Beat', 3: 'Charlie'}

Get the key 2 of the variable categories 

In [92]:
categories[2]

'Beat'

Insert the new column at df_new_cols and apply the values of categories

In [97]:
df_new_cols[new_cols] = df_new_cols[source_cols].applymap(categories.get) ; df_new_cols

AAA  BBB  CCC  AAA_cat BBB_cat  CCC_cat
0    1    1    2    Alpha   Alpha     Beat
1    2    1    1     Beat   Alpha    Alpha
2    1    2    3    Alpha    Beat  Charlie
3    3    2    1  Charlie    Beat    Alpha

---

Creat a DataFrame for variable df_group, use {'AAA': [1,1,1,2,2,2,3,3], 'BBB': [2,1,3,4,5,1,2,3]}

In [99]:
df_group = DataFrame({'AAA': [1,1,1,2,2,2,3,3], 'BBB':[2,1,3,4,5,1,2,3]}); df_group

AAA  BBB
0    1    2
1    1    1
2    1    3
3    2    4
4    2    5
5    2    1
6    3    2
7    3    3

About df_group, group by columns AAA, get the index of min value of columns BBB

In [123]:
df_group.groupby('AAA')['BBB'].idxmin()

AAA
1    1
2    5
3    6
Name: BBB, dtype: int64

About df_group, group by columns AAA, get the index of max value of columns BBB, use the index selection row

In [122]:
df_group.loc[df_group.groupby('AAA')['BBB'].idxmax()]

AAA  BBB
2    1    3
4    2    5
7    3    3

About df_group, sort value by columns BBB

In [108]:
df_group.sort_values(by='BBB')

AAA  BBB
1    1    1
5    2    1
0    1    2
6    3    2
2    1    3
7    3    3
3    2    4
4    2    5

About df_group, sort the columns BBB, group by columns AAA ,get the first value of each group

In [120]:
df_group.sort_values(by='BBB').groupby('AAA', as_index=False).first()

AAA  BBB
0    1    1
1    2    1
2    3    2

---

# pandas.Index.isin

In [18]:
help(pd.Index.isin)

Help on function isin in module pandas.core.indexes.base:

isin(self, values, level=None)
    Compute boolean array of whether each index value is found in the
    passed set of values.
    
    Parameters
    ----------
    values : set or list-like
        Sought values.
    
        .. versionadded:: 0.18.1
    
        Support for values as a set
    
    level : str or int, optional
        Name or position of the index level to use (if the index is a
        MultiIndex).
    
    Notes
    -----
    If `level` is specified:
    
    - if it is the name of one *and only one* index level, use that level;
    - otherwise it should be a number indicating level position.
    
    Returns
    -------
    is_contained : ndarray (boolean dtype)



In [19]:
df_isin = pd.DataFrame({'R1': [1, 1, 3, 5],  'R2': [0, 1, 2, 5], 'R3': [1, 5, 4, 1]}, index=['one', 'two', 'three', 'four']); df_isin

R1  R2  R3
one     1   0   1
two     1   1   5
three   3   2   4
four    5   5   1

In [20]:
df_isin.isin([1])

R1     R2     R3
one     True  False   True
two     True   True  False
three  False  False  False
four   False  False   True

In [21]:
df_isin.loc['one'].isin([1])

R1     True
R2    False
R3     True
Name: one, dtype: bool

In [22]:
df_isin.index.isin(['one'])

array([ True, False, False, False], dtype=bool)

In [23]:
df_isin.R1.isin([2])

one      False
two      False
three    False
four     False
Name: R1, dtype: bool

## pandas.date_range

In [24]:
help(pd.date_range)

Help on function date_range in module pandas.core.indexes.datetimes:

date_range(start=None, end=None, periods=None, freq='D', tz=None, normalize=False, name=None, closed=None, **kwargs)
    Return a fixed frequency datetime index, with day (calendar) as the default
    frequency
    
    Parameters
    ----------
    start : string or datetime-like, default None
        Left bound for generating dates
    end : string or datetime-like, default None
        Right bound for generating dates
    periods : integer or None, default None
        If None, must specify start and end
    freq : string or DateOffset, default 'D' (calendar daily)
        Frequency strings can have multiples, e.g. '5H'
    tz : string or None
        Time zone name for returning localized DatetimeIndex, for example
        Asia/Hong_Kong
    normalize : bool, default False
        Normalize start/end dates to midnight before generating date range
    name : str, default None
        Name of the resulting index
  

In [25]:
pd_date = pd.date_range('2017-11-12', periods=3, freq='1D'); pd_date

DatetimeIndex(['2017-11-12', '2017-11-13', '2017-11-14'], dtype='datetime64[ns]', freq='D')

# dict.get

In [26]:
help(dict.get)

Help on method_descriptor:

get(...)
    D.get(k[,d]) -> D[k] if k in D, else d.  d defaults to None.



In [27]:
categories

NameError: name 'categories' is not defined

In [ ]:
categories.get(1)

# pandas.DataFrame.applymap()

In [ ]:
help(pd.DataFrame.applymap)

applymap() 是 __element-wise__ 的,作用于每个 __DataFrame__ 的 __每个数据__

In [ ]:
df_isin

In [ ]:
df_isin.applymap(categories.get)

# pandas.DataFrame.sort_values

In [ ]:
help(pd.DataFrame.sort_values)

In [ ]:
df

In [ ]:
df.sort_values('AAA')

In [ ]:
df.sort_values(2,axis=1)

# pandas.DataFrame.groupby

In [ ]:
help(pd.DataFrame.groupby)

In [ ]:
df_group

In [ ]:
df_group.groupby('AAA')['BBB'].idxmin()

# pandas.core.groupby.GroupBy.first

In [ ]:
help(pd.core.groupby.GroupBy.first)

In [ ]:
df_group

In [ ]:
df_group.groupby('AAA')

In [ ]:
df_group.groupby('AAA',as_index=False).first()

# pandas.core.groupby.DataFrameGroupBy.idxmin

In [ ]:
help(pd.core.groupby.DataFrameGroupBy.idxmin)

In [ ]:
df_group

In [ ]:
df_group.groupby('AAA')

In [ ]:
df_group.groupby('AAA')['BBB']

In [ ]:
df_group.groupby('AAA').idxmin()

In [ ]:
df_group.groupby('AAA')['BBB'].idxmin()