# Selection

## DataFrames

In [356]:
import pandas as pd
from pandas import DataFrame, Series
import numpy as np

In [357]:
df = DataFrame({'AAA': [4, 5, 6, 7], 'BBB': [10, 20, 30, 40], 'CCC': [100, 50, -30, -50]}) ; df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

If 1, 2 are in index, return bool array

In [358]:
df.index.isin([1, 2])

array([False,  True,  True, False], dtype=bool)

aggregation bool series, use bool array and df colunns AAA is <= 6

In [359]:
(df.index.isin([1, 2])) & (df.AAA <= 6)

0    False
1     True
2     True
3    False
Name: AAA, dtype: bool

selection row index is 0, 2, 4 and columns AAA >= 6__

In [360]:
df.loc[(df.index.isin([0, 2, 4])) & (df.AAA >=6)]

AAA  BBB  CCC
2    6   30  -30

create dict "data", {'AAA': [4, 5, 6, 7], 'BBB': [10, 20, 30, 40], 'CCC': [100, 50, -30, -50]}

In [361]:
data = {'AAA': [4, 5, 6, 7], 'BBB': [10, 20 ,30 ,40], 'CCC': [100, 50, -30, -50]}

create DataFrame "df_d", data is "dict", index is 'foo', 'bar', 'boo', 'kar'

In [362]:
df_d = DataFrame(data = data, index = ['foo', 'bar', 'boo', 'kar']); df_d

AAA  BBB  CCC
foo    4   10  100
bar    5   20   50
boo    6   30  -30
kar    7   40  -50

inverse selection row, index is 'foo', 'boo' and columns AAA <= 6 

In [363]:
df_d.loc[(df_d.index.isin(['foo', 'boo'])) & (df_d.AAA <= 6)]

AAA  BBB  CCC
foo    4   10  100
boo    6   30  -30

selection row, position of df is 0~3

In [364]:
df_d.iloc[0:3]

AAA  BBB  CCC
foo    4   10  100
bar    5   20   50
boo    6   30  -30

selection row, index of df is 'bar'~'kar'

In [365]:
df_d.loc['bar':'kar']

AAA  BBB  CCC
bar    5   20   50
boo    6   30  -30
kar    7   40  -50

selection row , position of df2 is 1~3

In [366]:
df.iloc[1:3]

AAA  BBB  CCC
1    5   20   50
2    6   30  -30

selection row , index of df2 is 1~3

In [367]:
df.loc[1:3]

AAA  BBB  CCC
1    5   20   50
2    6   30  -30
3    7   40  -50

## Panels

creat Series "rng", from 1/1/2014, periods 100, freq 'D'

In [368]:
rng = pd.date_range('1/1/2014', periods=100, freq='D') ;  rng[:3]

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03'], dtype='datetime64[ns]', freq='D')

creat random array "data", [100[4]]

In [369]:
data = np.random.rand(100, 4) ; data[:3]

array([[ 0.96947314,  0.96071737,  0.65130933,  0.49048076],
       [ 0.78897614,  0.02590232,  0.03164667,  0.47355397],
       [ 0.49133571,  0.23326624,  0.44977054,  0.16598137]])

creat list, 'A', 'B', 'C', 'D'

In [370]:
cols = ['A', 'B', 'C', 'D'] ; cols

['A', 'B', 'C', 'D']

creat three DataFrame "df1", "df2", "df3", in data = data, index = rng, columns = cols

In [371]:
df1 = pd.DataFrame(data, rng, cols)
df2 = pd.DataFrame(data, rng, cols)
df3 = pd.DataFrame(data, rng, cols)

creat Panel "pf", use "df1", "df2", "df3", Items name is "df1", "df2", "df3"

In [372]:
pf = pd.Panel({'df1': df1, 'df2': df2, 'df3': df3}); pf

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 100 (major_axis) x 4 (minor_axis)
Items axis: df1 to df3
Major_axis axis: 2014-01-01 00:00:00 to 2014-04-10 00:00:00
Minor_axis axis: A to D

### New Columns

creat DataFrame "df_new_cols", use {'AAA': [1,2,1,3], 'BBB': [1,1,2,2], 'CCC': [2,1,3,1]}

In [373]:
df_new_cols = pd.DataFrame({'AAA': [1,2,1,3], 'BBB': [1,1,2,2], 'CCC': [2,1,3,1]}); df_new_cols

AAA  BBB  CCC
0    1    1    2
1    2    1    1
2    1    2    3
3    3    2    1

creat Index "source_cols", use df_new_cols columns

In [374]:
source_cols = df_new_cols.columns; source_cols

Index(['AAA', 'BBB', 'CCC'], dtype='object')

creat list "new_cols", use "df_new_cols" columns + '_cat'

In [375]:
new_cols = [str(x) + '_cat' for x in source_cols]; new_cols

['AAA_cat', 'BBB_cat', 'CCC_cat']

creat dict "categories", as {1: 'Alpha', 2: 'Beta', 3: 'Charlie'}

In [376]:
categories = {1: 'Alpha', 2: 'Beta', 3: 'Charlie'}

get "categories" key 2

In [377]:
categories.get(2)

'Beta'

new columns, add "new_cols" and based on the original value apply new_cols's values by categories's value

In [378]:
df_new_cols[new_cols] = df_new_cols.applymap(categories.get); df_new_cols

AAA  BBB  CCC  AAA_cat BBB_cat  CCC_cat
0    1    1    2    Alpha   Alpha     Beta
1    2    1    1     Beta   Alpha    Alpha
2    1    2    3    Alpha    Beta  Charlie
3    3    2    1  Charlie    Beta    Alpha

creat DataFrame "df_group", use {'AAA': [1,1,1,2,2,2,3,3], 'BBB': [2,1,3,4,5,1,2,3]}

In [379]:
df_group = pd.DataFrame({'AAA': [1,1,1,2,2,2,3,3], 'BBB': [2,1,3,4,5,1,2,3]}); df_group

AAA  BBB
0    1    2
1    1    1
2    1    3
3    2    4
4    2    5
5    2    1
6    3    2
7    3    3

creat Series "idx", get df_group's index of min value

In [380]:
idx = df_group.groupby('AAA')['BBB'].idxmin() ; idx

AAA
1    1
2    5
3    6
Name: BBB, dtype: int64

selection row, by idx

In [381]:
df_group.loc[idx]

AAA  BBB
1    1    1
5    2    1
6    3    2

sort value by df_group columns BBB

In [382]:
df_group.sort_values(by='BBB')

AAA  BBB
1    1    1
5    2    1
0    1    2
6    3    2
2    1    3
7    3    3
3    2    4
4    2    5

先将BBB排序,在根据AAA分组,获取每个分组的第一个值

In [383]:
df_group.sort_values(by='BBB').groupby('AAA', as_index=False).first()

AAA  BBB
0    1    1
1    2    1
2    3    2

---

# pandas.Index.isin

In [432]:
help(pd.Index.isin)

Help on function isin in module pandas.core.indexes.base:

isin(self, values, level=None)
    Compute boolean array of whether each index value is found in the
    passed set of values.
    
    Parameters
    ----------
    values : set or list-like
        Sought values.
    
        .. versionadded:: 0.18.1
    
        Support for values as a set
    
    level : str or int, optional
        Name or position of the index level to use (if the index is a
        MultiIndex).
    
    Notes
    -----
    If `level` is specified:
    
    - if it is the name of one *and only one* index level, use that level;
    - otherwise it should be a number indicating level position.
    
    Returns
    -------
    is_contained : ndarray (boolean dtype)



In [413]:
df_isin = pd.DataFrame({'R1': [1, 1, 3, 5],  'R2': [0, 1, 2, 5], 'R3': [1, 5, 4, 1]}, index=['one', 'two', 'three', 'four']); df_isin

R1  R2  R3
one     1   0   1
two     1   1   5
three   3   2   4
four    5   5   1

In [386]:
df_isin.isin([1])

R1     R2     R3
one     True  False   True
two     True   True  False
three  False  False  False
four   False  False   True

In [387]:
df_isin.loc['one'].isin([1])

R1     True
R2    False
R3     True
Name: one, dtype: bool

In [388]:
df_isin.index.isin(['one'])

array([ True, False, False, False], dtype=bool)

In [389]:
df_isin.R1.isin([2])

one      False
two      False
three    False
four     False
Name: R1, dtype: bool

---

## pandas.date_range

In [430]:
help(pd.date_range)

Help on function date_range in module pandas.core.indexes.datetimes:

date_range(start=None, end=None, periods=None, freq='D', tz=None, normalize=False, name=None, closed=None, **kwargs)
    Return a fixed frequency datetime index, with day (calendar) as the default
    frequency
    
    Parameters
    ----------
    start : string or datetime-like, default None
        Left bound for generating dates
    end : string or datetime-like, default None
        Right bound for generating dates
    periods : integer or None, default None
        If None, must specify start and end
    freq : string or DateOffset, default 'D' (calendar daily)
        Frequency strings can have multiples, e.g. '5H'
    tz : string or None
        Time zone name for returning localized DatetimeIndex, for example
        Asia/Hong_Kong
    normalize : bool, default False
        Normalize start/end dates to midnight before generating date range
    name : str, default None
        Name of the resulting index
  

In [391]:
pd_date = pd.date_range('2017-11-12', periods=3, freq='1D'); pd_date

DatetimeIndex(['2017-11-12', '2017-11-13', '2017-11-14'], dtype='datetime64[ns]', freq='D')

---

# dict.get

In [433]:
help(dict.get)

Help on method_descriptor:

get(...)
    D.get(k[,d]) -> D[k] if k in D, else d.  d defaults to None.



In [415]:
categories

{1: 'Alpha', 2: 'Beta', 3: 'Charlie'}

In [393]:
categories.get(1)

'Alpha'

---

# pandas.DataFrame.applymap()

In [429]:
help(pd.DataFrame.applymap)

Help on function applymap in module pandas.core.frame:

applymap(self, func)
    Apply a function to a DataFrame that is intended to operate
    elementwise, i.e. like doing map(func, series) for each series in the
    DataFrame
    
    Parameters
    ----------
    func : function
        Python function, returns a single value from a single value
    
    Examples
    --------
    
    >>> df = pd.DataFrame(np.random.randn(3, 3))
    >>> df
        0         1          2
    0  -0.029638  1.081563   1.280300
    1   0.647747  0.831136  -1.549481
    2   0.513416 -0.884417   0.195343
    >>> df = df.applymap(lambda x: '%.2f' % x)
    >>> df
        0         1          2
    0  -0.03      1.08       1.28
    1   0.65      0.83      -1.55
    2   0.51     -0.88       0.20
    
    Returns
    -------
    applied : DataFrame
    
    See also
    --------
    DataFrame.apply : For operations on rows/columns



applymap() 是 __element-wise__ 的,作用于每个 __DataFrame__ 的 __每个数据__

In [414]:
df_isin

R1  R2  R3
one     1   0   1
two     1   1   5
three   3   2   4
four    5   5   1

In [395]:
df_isin.applymap(categories.get)

R1     R2     R3
one      Alpha   None  Alpha
two      Alpha  Alpha   None
three  Charlie   Beta   None
four      None   None  Alpha

---

# pandas.DataFrame.sort_values

In [396]:
help(pd.DataFrame.sort_values)

Help on function sort_values in module pandas.core.frame:

sort_values(self, by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')
    Sort by the values along either axis
    
    .. versionadded:: 0.17.0
    
    Parameters
    ----------
    by : str or list of str
        Name or list of names which refer to the axis items.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Axis to direct sorting
    ascending : bool or list of bool, default True
         Sort ascending vs. descending. Specify list for multiple sort
         orders.  If this is a list of bools, must match the length of
         the by.
    inplace : bool, default False
         if True, perform operation in-place
    kind : {'quicksort', 'mergesort', 'heapsort'}, default 'quicksort'
         Choice of sorting algorithm. See also ndarray.np.sort for more
         information.  `mergesort` is the only stable algorithm. For
         DataFrames, this option is only applied when sort

In [397]:
df

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [398]:
df.sort_values('AAA')

AAA  BBB  CCC
0    4   10  100
1    5   20   50
2    6   30  -30
3    7   40  -50

In [399]:
df.sort_values(2,axis=1)

CCC  AAA  BBB
0  100    4   10
1   50    5   20
2  -30    6   30
3  -50    7   40

---

# pandas.DataFrame.groupby

In [400]:
help(pd.DataFrame.groupby)

Help on function groupby in module pandas.core.generic:

groupby(self, by=None, axis=0, level=None, as_index=True, sort=True, group_keys=True, squeeze=False, **kwargs)
    Group series using mapper (dict or key function, apply given function
    to group, return result as series) or by a series of columns.
    
    Parameters
    ----------
    by : mapping, function, str, or iterable
        Used to determine the groups for the groupby.
        If ``by`` is a function, it's called on each value of the object's
        index. If a dict or Series is passed, the Series or dict VALUES
        will be used to determine the groups (the Series' values are first
        aligned; see ``.align()`` method). If an ndarray is passed, the
        values are used as-is determine the groups. A str or list of strs
        may be passed to group by the columns in ``self``
    axis : int, default 0
    level : int, level name, or sequence of such, default None
        If the axis is a MultiIndex (hierar

In [401]:
df_group

AAA  BBB
0    1    2
1    1    1
2    1    3
3    2    4
4    2    5
5    2    1
6    3    2
7    3    3

In [402]:
df_group.groupby('AAA')['BBB'].idxmin()

AAA
1    1
2    5
3    6
Name: BBB, dtype: int64

---

# pandas.core.groupby.GroupBy.first

In [403]:
help(pd.core.groupby.GroupBy.first)

Help on function first in module pandas.core.groupby:

first(self, **kwargs)
    Compute first of group values
    
    See also
    --------
    pandas.Series.groupby
    pandas.DataFrame.groupby
    pandas.Panel.groupby



In [404]:
df_group

AAA  BBB
0    1    2
1    1    1
2    1    3
3    2    4
4    2    5
5    2    1
6    3    2
7    3    3

In [405]:
df_group.groupby('AAA')

In [406]:
df_group.groupby('AAA',as_index=False).first()

AAA  BBB
0    1    2
1    2    4
2    3    2

---

# pandas.core.groupby.DataFrameGroupBy.idxmin

In [407]:
help(pd.core.groupby.DataFrameGroupBy.idxmin)

Help on property:

    Return index of first occurrence of minimum over requested axis.
    NA/null values are excluded.
    
    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        0 or 'index' for row-wise, 1 or 'columns' for column-wise
    skipna : boolean, default True
        Exclude NA/null values. If an entire row/column is NA, the result
        will be NA
    
    Returns
    -------
    idxmin : Series
    
    Notes
    -----
    This method is the DataFrame version of ``ndarray.argmin``.
    
    See Also
    --------
    Series.idxmin



In [408]:
df_group

AAA  BBB
0    1    2
1    1    1
2    1    3
3    2    4
4    2    5
5    2    1
6    3    2
7    3    3

In [409]:
df_group.groupby('AAA')

In [410]:
df_group.groupby('AAA')['BBB']

In [411]:
df_group.groupby('AAA').idxmin()

BBB
AAA     
1      1
2      5
3      6

In [412]:
df_group.groupby('AAA')['BBB'].idxmin()

AAA
1    1
2    5
3    6
Name: BBB, dtype: int64